cabal-version:      3.0
name:               imtt
version:            0.1.0.0
-- synopsis:
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             ANONYMOUS
maintainer:         ANONYMOUS@ANONYMOUS.ANONYMOUS
category:           Language
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common stanzas
    ghc-options:        -Wall -Werror
    default-language:   GHC2024
    default-extensions: BlockArguments

library
    import:          stanzas
    exposed-modules: Source
    -- other-modules:
    build-depends:   base >=4.21 && <5, megaparsec, text
    hs-source-dirs:  src

executable imtt
    import:         stanzas
    main-is:        Main.hs
    -- other-modules:
    build-depends:  base, imtt, haskeline
    hs-source-dirs: app

test-suite imtt-test
    import:         stanzas
    -- other-modules:
    type:           exitcode-stdio-1.0
    hs-source-dirs: test
    main-is:        Main.hs
    build-depends:  base, imtt
